global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'react_app'
    scrape_interval: 15s
    static_configs:
      - targets: ['my-app-react:4173']
